'use client';

import { useMissionStore } from '@/lib/store';

/**
 * Permanent footer disclosure.
 *
 * This dashboard is realistic enough to be mistaken for a real ground segment,
 * so it states plainly and at all times that nothing here is connected to a
 * spacecraft. It also surfaces where telemetry history is being written, which
 * tells the operator whether PostgreSQL is actually up.
 */
export function SimulationNotice() {
  const mission = useMissionStore((s) => s.mission);
  const connected = useMissionStore((s) => s.connected);

  return (
    <footer className="flex shrink-0 items-center justify-between gap-3 border-t border-line bg-panel px-3 py-1">
      <span className="truncate font-mono text-[9.5px] uppercase tracking-[0.1em] text-ink-muted">
        <span className="text-[var(--warn)]">▲ Simulation only</span> — no real spacecraft, RF
        hardware or ground station. All values are generated by the on-server simulation engines.
      </span>
      <span className="hidden shrink-0 font-mono text-[9.5px] tracking-[0.06em] text-ink-muted md:inline">
        {mission?.operator ?? 'K. J. Somaiya Institute of Technology'}
        {' · history → '}
        <span className={mission?.persistence === 'POSTGRES' ? 'text-[var(--nominal)]' : 'text-[var(--warn)]'}>
          {mission?.persistence === 'POSTGRES' ? 'PostgreSQL' : 'in-memory (Postgres down)'}
        </span>
        {' · '}
        <span className={connected ? 'text-[var(--nominal)]' : 'text-[var(--critical)]'}>
          {connected ? 'socket.io live' : 'stream offline'}
        </span>
      </span>
    </footer>
  );
}