/**
 * KJS-SRS-01 — SomaiyaSat & SomaiyaPod mission control backend.
 *
 * SIMULATION ONLY. No RF hardware, no spacecraft and no ground station are
 * involved anywhere in this process. Every value it publishes is generated by
 * the engines under src/sim.
 */

// './config' must be imported before './db/prisma' — it loads .env and supplies
// the DATABASE_URL default that Prisma's constructor requires.
import { config } from './config';

import cors from 'cors';
import express from 'express';
import { createServer } from 'http';
import { connectDatabase, prisma } from './db/prisma';
import { history } from './db/history';
import { api } from './routes/api';
import { simulation } from './sim/simulation';
import { createSocketServer } from './socket';

async function main(): Promise<void> {
  const app = express();
  app.use(cors({ origin: config.corsOrigin }));
  app.use(express.json());

  app.use('/api', api);
  app.get('/', (_req, res) => {
    res.json({
      service: `${config.mission.designator} mission control backend`,
      notice: 'Simulated academic demonstrator — no real satellite or RF hardware.',
      socket: 'socket.io on this same origin',
      rest: '/api/health, /api/snapshot, /api/history/:channel, /api/events, /api/commands',
    });
  });

  const httpServer = createServer(app);
  createSocketServer(httpServer);

  // Without this, a port clash surfaces as an unhandled 'error' event and a raw
  // stack trace, which reads as a crash rather than as "something else is
  // already running here".
  httpServer.on('error', (err: NodeJS.ErrnoException) => {
    if (err.code === 'EADDRINUSE') {
      console.error(
        `\n[sim] port ${config.port} is already in use — another instance of the ` +
          'simulation backend is probably running.\n' +
          '[sim] stop it, or set PORT in backend/.env to a free port.\n',
      );
    } else {
      console.error('[sim] http server error', err);
    }
    process.exit(1);
  });

  await connectDatabase();
  simulation.start();

  httpServer.listen(config.port, () => {
    console.log(`\n  ${config.mission.designator} — ${config.mission.name}`);
    console.log(`  simulation backend listening on http://localhost:${config.port}`);
    console.log(`  sim epoch ${new Date(config.epoch).toISOString()} @ ${config.speed}x`);
    console.log(`  SIMULATED DATA ONLY — no real spacecraft or RF hardware\n`);
  });

  const shutdown = async (signal: string) => {
    console.log(`\n[sim] ${signal} received, shutting down`);
    simulation.stop();
    await history.flush();
    await prisma.$disconnect().catch(() => undefined);
    httpServer.close(() => process.exit(0));
    // Don't hang forever on a stuck socket.
    setTimeout(() => process.exit(0), 3000).unref();
  };

  process.on('SIGINT', () => void shutdown('SIGINT'));
  process.on('SIGTERM', () => void shutdown('SIGTERM'));
}

main().catch((err) => {
  console.error('[sim] fatal startup error', err);
  process.exit(1);
});